---
- name: iloveansible
  hosts: linux
  become: yes
  tasks:
    - name: Ensure nano is there
      yum:
        name: nano
        state: absent
    - name: Ensure curl is there
      yum:
        name: curl
        state: latest
