Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-8"
  
    config.vm.define "server1" do |server1|
      server1.vm.network "private_network", ip: "192.168.0.1", name: 'vboxnet0'
      server1.vm.hostname = "server1.local"
      server1.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
      server1.vm.network :forwarded_port, guest: 22, host: 2230, auto_correct: true
      server1.ssh.port = 2230
      server1.vm.provider "server1" do |vb|
        vb.cpus = 1
        vb.memory = 1024
      end
    end

    config.vm.define "server2" do |server2|
      server2.vm.network "private_network", ip: "192.168.1.1", name: 'vboxnet1'
      server2.vm.hostname = "server2.local"
      server2.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
      server2.vm.network :forwarded_port, guest: 22, host: 2231, auto_correct: true
      server2.ssh.port = 2231
      server2.vm.provider "server2" do |vb|
        vb.cpus = 1
        vb.memory = 1024
      end
    end
  end