Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-7"
  
    config.vm.define "server" do |server|
      server.vm.network "private_network", ip: "192.168.0.1", name: 'vboxnet0'
      server.vm.hostname = "server.local"
      server.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
      server.vm.network :forwarded_port, guest: 22, host: 2230, auto_correct: true
      server.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true
      server.ssh.port = 2230
      server.vm.provider "server" do |vb|
        vb.cpus = 1
        vb.memory = 1024
      end
    end
  end
  